IF(NOT DEFINED CMAKE_CURRENT_LIST_DIR)
	GET_FILENAME_COMPONENT(CMAKE_CURRENT_LIST_DIR ${CMAKE_CURRENT_LIST_FILE} PATH)
ENDIF (NOT DEFINED CMAKE_CURRENT_LIST_DIR)
MESSAGE("${CMAKE_CURRENT_LIST_DIR}")
IF(NOT DEFINED AC_ROOT_DIR)
	SET(AC_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/../")
ENDIF(NOT DEFINED AC_ROOT_DIR)
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${LABS_ROOT_DIR}/cmake/")

SET (FLAGS_DEFAULT "-fPIC -pipe")
SET (FLAGS_WARNING 	"-Wall -Werror -Wextra -pedantic -Winit-self -Wconversion")

SET (FLAGS_CXX_LANG "-std=c++11")
SET (FLAGS_WARNING_CXX "${FLAGS_WARNING} -Weffc++ -Wold-style-cast -Woverloaded-virtual -Wshadow -Wctor-dtor-privacy -Wnon-virtual-dtor")
SET (FLAGS_RELEASE "-ggdb -O2")
SET (FLAGS_DEBUG "-ggdb -O2")
MESSAGE("Build type is ${CMAKE_BUILD_TYPE}")
function(disable_warnings)
	SET (CMAKE_C_FLAGS_DEBUG "${FLAGS_DEFAULT} ${FLAGS_DEBUG}" PARENT_SCOPE)
	SET (CMAKE_C_FLAGS_RELEASE "${FLAGS_DEFAULT} ${FLAGS_RELEASE}" PARENT_SCOPE)
	SET (CMAKE_C_FLAGS_RELWITHDEBINFO "${FLAGS_DEFAULT} ${FLAGS_DEBUG} ${FLAGS_RELEASE}" PARENT_SCOPE)
	SET (CMAKE_CXX_FLAGS_DEBUG "${FLAGS_DEFAULT} ${FLAGS_DEBUG} ${FLAGS_CXX_LANG} -Wno-deprecated-declarations -Wno-deprecated" PARENT_SCOPE)
	SET (CMAKE_CXX_FLAGS_RELEASE "${FLAGS_DEFAULT} ${FLAGS_RELEASE} ${FLAGS_CXX_LANG} -Wno-deprecated-declarations -Wno-deprecated" PARENT_SCOPE)
	SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "${FLAGS_DEFAULT} ${FLAGS_RELEASE} ${FLAGS_CXX_LANG} -Wno-deprecated-declarations -Wno-deprecated" PARENT_SCOPE)
endfunction(disable_warnings)

function(enable_warnings)
	SET (CMAKE_C_FLAGS_DEBUG "${FLAGS_DEFAULT} ${FLAGS_WARNING} ${FLAGS_DEBUG}" PARENT_SCOPE)
	SET (CMAKE_C_FLAGS_RELEASE "${FLAGS_DEFAULT} ${FLAGS_WARNING} ${FLAGS_RELEASE}" PARENT_SCOPE)
	SET (CMAKE_C_FLAGS_RELWITHDEBINFO "${FLAGS_DEFAULT} ${FLAGS_WARNING} ${FLAGS_DEBUG} ${FLAGS_RELEASE}" PARENT_SCOPE)

	SET (CMAKE_CXX_FLAGS_DEBUG "${FLAGS_DEFAULT} ${FLAGS_WARNING_CXX} ${FLAGS_DEBUG} ${FLAGS_CXX_LANG}" PARENT_SCOPE)
	SET (CMAKE_CXX_FLAGS_RELEASE "${FLAGS_DEFAULT} ${FLAGS_WARNING_CXX} ${FLAGS_RELEASE} ${FLAGS_CXX_LANG}" PARENT_SCOPE)
	SET (CMAKE_CXX_FLAGS_RELWITHDEBINFO "${FLAGS_DEFAULT} ${FLAGS_WARNING_CXX} ${FLAGS_RELEASE} ${FLAGS_CXX_LANG}" PARENT_SCOPE)
endfunction(enable_warnings)

enable_warnings()

IF (NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
  SET (CMAKE_BUILD_TYPE RELEASE)
  SET (CMAKE_BUILD_TYPE RELEASE CACHE STRING "Build type" FORCE)
ENDIF (NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)

IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
	SET(CMAKE_OSX_SYSROOT "")
	SET(CMAKE_OSX_DEPLOYMENT_TARGET "")
	SET(CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem")
	INCLUDE_DIRECTORIES(
		SYSTEM
		/opt/local/include
		/usr/local/include
	)
	LINK_DIRECTORIES(/opt/local/lib)
	LINK_DIRECTORIES(/opt/local/lib/mysql55/mysql/)
	SET(OperatingSystem "Mac OS X")
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")

IF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
	SET(OperatingSystem "Linux")
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")

